name: 'Docker Run Command'
description: 'Run a command in a new container'
author: 'Sergei Predvoditelev'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  image:
    description: 'Docker image to run (e.g. ubuntu:24.04, python:3.12)'
    required: true
  registry:
    description: 'Docker registry URL for authentication (e.g. ghcr.io, docker.io)'
    required: false
    default: ''
  username:
    description: 'Username for Docker registry authentication'
    required: false
    default: ''
  password:
    description: 'Password or token for Docker registry authentication'
    required: false
    default: ''
  options:
    description: 'Additional docker run options (e.g. --network host --cpus 2)'
    required: false
    default: ''
  volumes:
    description: 'Volume mounts, one per line (e.g. /host/path:/container/path)'
    required: false
    default: ''
  env:
    description: 'Environment variables, one per line (e.g. MY_VAR=some value)'
    required: false
    default: ''
  workdir:
    description: 'Working directory inside the container'
    required: false
    default: ''
  command:
    description: 'Shell command to run inside the container'
    required: true
runs:
  using: 'composite'
  steps:
    - shell: sh
      env:
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_OPTIONS: ${{ inputs.options }}
        INPUT_VOLUMES: ${{ inputs.volumes }}
        INPUT_ENV: ${{ inputs.env }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_COMMAND: ${{ inputs.command }}
      run: ${{ github.action_path }}/action.sh
